FROM jenkins/jenkins:lts-jdk17
USER root
RUN jenkins-plugin-cli --plugins \
    configuration-as-code:latest \
    job-dsl:latest \
    git:latest \
    workflow-aggregator:latest \
    credentials-binding:latest
USER jenkins
